name = "derbynames-api"
main = "src/index.ts"
compatibility_date = "2024-03-20"
compatibility_flags = ["nodejs_compat"]
kv_namespaces = [
    { binding = "derbyname", id = "b6fb1f7f7d7c415887f48ad8030d7c72", preview_id = "ad81321a283d4b2e82d8361d073d4d7a" }
]

[env.production]
name = "derbynames-api"
vars = { ENVIRONMENT = "production" }



[env.development]
name = "derbynames-api-dev"
vars = { ENVIRONMENT = "development" }

