name = "derbynames-api"
main = "src/index.ts"
compatibility_date = "2024-03-20"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "derbynames-api"
vars = { ENVIRONMENT = "production" }

[env.development]
name = "derbynames-api-dev"
vars = { ENVIRONMENT = "development" }